<a href="https://colab.research.google.com/github/leogold/AI_sandbox/blob/master/Sodoku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
sodoku=[[5,3,0,0,7,0,0,0,0],[6,0,0,1,9,5,0,0,0],[0,9,8,0,0,0,0,6,0],[8,0,0,0,6,0,0,0,3],[4,0,0,8,0,3,0,0,1],[7,0,0,0,2,0,0,0,6],[0,6,0,0,0,0,2,8,0,],[0,0,0,4,1,9,0,0,5],[0,0,0,0,8,0,0,7,9]]

In [4]:
print(np.matrix(sodoku))


[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [0]:
def pode (y,x,n):
    global sodoku
    for i in range(9):
        if sodoku[y][i] == n:
            return False
    for i in range(9):
        if sodoku[i][x] == n:
            return False
    ys = (y//3)*3
    xs = (x//3)*3
    for i in range (3):
        for j in range (3):
            if sodoku [ys+i][xs+j] == n:
                #print (sodoku[ys+i][xs+j])
                return False
    return True

In [6]:
pode(4,4,5)

True

In [0]:
def resolve() :
    global sodoku
    for y in range(9) :
        for x in range(9) :
            if sodoku[y][x] == 0 :
                for n in range(1,10) : # para antes de ultimo, no caso nao pega o 10
                    if pode (y,x,n) :
                        sodoku[y][x] = n
                        resolve()
                        sodoku[y][x] = 0
                solved = (y,x,n)
                return
    print(np.matrix(sodoku))
    input("será que existem mais soluções?")

In [8]:
resolve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
será que existem mais soluções?


In [0]:
sodoku=[[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]]

In [0]:
sodoku=[[5,3,0,0,7,0,0,0,0],[6,0,0,1,9,5,0,0,0],[0,9,8,0,0,0,0,6,0],[8,0,0,0,6,0,0,0,3],[4,0,0,8,0,3,0,0,1],[7,0,0,0,2,0,0,0,6],[0,6,0,0,0,0,2,8,0,],[0,0,0,4,1,9,0,0,5],[0,0,0,0,8,0,0,0,0]]

In [0]:
def pode2 (y,x):
    global sodoku
    lista = []
    for i in range(9):
        lista.append(sodoku[y][i])
    for i in range(9):
        lista.append(sodoku[i][x])
    ys = (y//3)*3
    xs = (x//3)*3
    for i in range (3):
        for j in range (3):
            lista.append(sodoku [ys+i][xs+j])
    unicos = np.unique(lista)
    #print (unicos)
    #print(np.count_nonzero(unicos))
    if np.count_nonzero(unicos) == 8:
        return True
    return False

In [0]:
def resolve2() :
    global sodoku
    for y in range(9) :
        for x in range(9) :
            if sodoku[y][x] == 0  & pode2 (y,x):
                for n in range(1,10) : # para antes de ultimo, no caso nao pega o 10
                    if pode (y,x,n):
                        sodoku[y][x] = n
                        resolve2()
                        sodoku[y][x] = 0
                solved = (y,x,n)
                return
    print(np.matrix(sodoku))
    input("será que existem mais soluções?")

In [13]:
resolve2()

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
será que existem mais soluções?
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
será que existem mais soluções?
